// Generated by scripts/gen-illustration-index.mjs from the manifest. Do not edit.
export type IllustrationMeta = { w: number; h: number; c: string; alt: string; svg: boolean }
export const ILLUSTRATIONS = {
 "empty-no-papers": {
  "w": 375,
  "h": 393,
  "c": "empty-state",
  "alt": "No papers filed yet",
  "svg": true
 },
 "empty-nothing-to-review": {
  "w": 467,
  "h": 239,
  "c": "empty-state",
  "alt": "Review queue is clear",
  "svg": true
 },
 "empty-no-messages": {
  "w": 320,
  "h": 344,
  "c": "empty-state",
  "alt": "No messages or no thread selected",
  "svg": true
 },
 "empty-no-results": {
  "w": 380,
  "h": 310,
  "c": "empty-state",
  "alt": "Search returned nothing",
  "svg": true
 },
 "empty-calendar": {
  "w": 442,
  "h": 335,
  "c": "empty-state",
  "alt": "No events or deadlines",
  "svg": true
 },
 "not-found-404": {
  "w": 426,
  "h": 187,
  "c": "error-state",
  "alt": "Page not found",
  "svg": true
 },
 "file-from-index": {
  "w": 436,
  "h": 346,
  "c": "filing-method",
  "alt": "Filing option: pick the paper from the Scopus/indexed list",
  "svg": true
 },
 "file-paste-doi": {
  "w": 415,
  "h": 355,
  "c": "filing-method",
  "alt": "Filing option: paste a DOI",
  "svg": true
 },
 "file-by-hand": {
  "w": 452,
  "h": 347,
  "c": "filing-method",
  "alt": "Filing option: type the details by hand",
  "svg": true
 },
 "leaderboard-honours": {
  "w": 442,
  "h": 370,
  "c": "page-spot",
  "alt": "Leaderboard / honours header",
  "svg": true
 },
 "discover-ideas": {
  "w": 437,
  "h": 387,
  "c": "page-spot",
  "alt": "Discover / research ideas",
  "svg": true
 },
 "collaboration": {
  "w": 460,
  "h": 300,
  "c": "page-spot",
  "alt": "Collaboration / people working together",
  "svg": true
 },
 "hero-research-scout": {
  "w": 1600,
  "h": 900,
  "c": "hero",
  "alt": "Research scout page header",
  "svg": false
 },
 "hero-sign-in": {
  "w": 1360,
  "h": 765,
  "c": "hero",
  "alt": "Sign-in page scene (primary)",
  "svg": false
 },
 "hero-sign-in-alt": {
  "w": 1156,
  "h": 650,
  "c": "hero",
  "alt": "Sign-in page scene (alternate)",
  "svg": false
 },
 "spot-home-faculty": {
  "w": 465,
  "h": 356,
  "c": "page-spot",
  "alt": "Faculty home header",
  "svg": false
 },
 "spot-home-hod": {
  "w": 471,
  "h": 366,
  "c": "page-spot",
  "alt": "Head of department home header",
  "svg": false
 },
 "spot-home-admin": {
  "w": 462,
  "h": 357,
  "c": "page-spot",
  "alt": "Administration home header",
  "svg": false
 },
 "spot-search": {
  "w": 440,
  "h": 363,
  "c": "page-spot",
  "alt": "Search header",
  "svg": false
 },
 "spot-my-papers": {
  "w": 445,
  "h": 413,
  "c": "page-spot",
  "alt": "My papers header",
  "svg": false
 },
 "spot-my-research": {
  "w": 455,
  "h": 423,
  "c": "page-spot",
  "alt": "My research header",
  "svg": false
 },
 "spot-who-to-work-with": {
  "w": 444,
  "h": 360,
  "c": "page-spot",
  "alt": "Who to work with header",
  "svg": false
 },
 "spot-profile": {
  "w": 356,
  "h": 338,
  "c": "page-spot",
  "alt": "Profile header",
  "svg": true
 },
 "spot-messages": {
  "w": 428,
  "h": 353,
  "c": "page-spot",
  "alt": "Messages header",
  "svg": true
 },
 "spot-discussions": {
  "w": 412,
  "h": 424,
  "c": "page-spot",
  "alt": "Discussions header",
  "svg": false
 },
 "spot-wall-of-fame": {
  "w": 433,
  "h": 402,
  "c": "page-spot",
  "alt": "Wall of fame header",
  "svg": true
 },
 "spot-calendar": {
  "w": 422,
  "h": 341,
  "c": "page-spot",
  "alt": "Calendar header",
  "svg": true
 },
 "spot-notifications": {
  "w": 346,
  "h": 263,
  "c": "page-spot",
  "alt": "Notifications header",
  "svg": true
 },
 "spot-settings": {
  "w": 404,
  "h": 302,
  "c": "page-spot",
  "alt": "Settings header",
  "svg": true
 },
 "spot-approvals": {
  "w": 378,
  "h": 314,
  "c": "page-spot",
  "alt": "Clearing / approvals header",
  "svg": true
 },
 "spot-authorisations": {
  "w": 352,
  "h": 352,
  "c": "page-spot",
  "alt": "Authorisations header",
  "svg": true
 },
 "spot-payouts": {
  "w": 427,
  "h": 281,
  "c": "page-spot",
  "alt": "Incentives / payments header",
  "svg": true
 },
 "spot-people": {
  "w": 385,
  "h": 277,
  "c": "page-spot",
  "alt": "People directory header",
  "svg": true
 },
 "spot-imports": {
  "w": 348,
  "h": 420,
  "c": "page-spot",
  "alt": "Imports header",
  "svg": true
 },
 "spot-flags": {
  "w": 405,
  "h": 336,
  "c": "page-spot",
  "alt": "Flags / follow-ups header",
  "svg": true
 },
 "spot-archive": {
  "w": 408,
  "h": 310,
  "c": "page-spot",
  "alt": "Archive header",
  "svg": true
 },
 "spot-audit": {
  "w": 441,
  "h": 312,
  "c": "page-spot",
  "alt": "Audit trail header",
  "svg": true
 },
 "spot-reports": {
  "w": 273,
  "h": 395,
  "c": "page-spot",
  "alt": "Reports header",
  "svg": true
 },
 "spot-accreditation": {
  "w": 353,
  "h": 354,
  "c": "page-spot",
  "alt": "Accreditation header",
  "svg": true
 },
 "spot-budget": {
  "w": 432,
  "h": 331,
  "c": "page-spot",
  "alt": "Budget header",
  "svg": true
 },
 "spot-policy": {
  "w": 427,
  "h": 379,
  "c": "page-spot",
  "alt": "Policy header",
  "svg": true
 },
 "spot-setup": {
  "w": 432,
  "h": 328,
  "c": "page-spot",
  "alt": "Setup / first-run configuration header",
  "svg": true
 },
 "spot-privacy": {
  "w": 424,
  "h": 343,
  "c": "page-spot",
  "alt": "Privacy header",
  "svg": true
 },
 "error-server": {
  "w": 492,
  "h": 216,
  "c": "error-state",
  "alt": "Server error (500) — unplugged cable",
  "svg": true
 },
 "error-offline": {
  "w": 397,
  "h": 383,
  "c": "error-state",
  "alt": "Offline / connection lost (renders as a cracked laptop screen under a cloud; use with clear copy)",
  "svg": true
 },
 "empty-no-notifications": {
  "w": 354,
  "h": 268,
  "c": "empty-state",
  "alt": "No notifications",
  "svg": true
 },
 "empty-no-discussions": {
  "w": 460,
  "h": 463,
  "c": "empty-state",
  "alt": "No discussions yet",
  "svg": true
 },
 "empty-no-badges": {
  "w": 424,
  "h": 374,
  "c": "empty-state",
  "alt": "No badges earned yet",
  "svg": true
 },
 "empty-no-collaborators": {
  "w": 426,
  "h": 307,
  "c": "empty-state",
  "alt": "No collaborators yet",
  "svg": true
 },
 "empty-no-flags": {
  "w": 414,
  "h": 402,
  "c": "empty-state",
  "alt": "No open flags — all clear",
  "svg": true
 },
 "empty-no-imports": {
  "w": 449,
  "h": 328,
  "c": "empty-state",
  "alt": "Nothing imported yet",
  "svg": true
 },
 "empty-no-drafts": {
  "w": 417,
  "h": 380,
  "c": "empty-state",
  "alt": "No drafts",
  "svg": true
 },
 "error-access-denied": {
  "w": 423,
  "h": 416,
  "c": "error-state",
  "alt": "Access restricted (403)",
  "svg": true
 },
 "error-session-expired": {
  "w": 391,
  "h": 375,
  "c": "error-state",
  "alt": "Session expired — sign in again",
  "svg": true
 },
 "error-upload-failed": {
  "w": 414,
  "h": 349,
  "c": "error-state",
  "alt": "Upload failed — try again",
  "svg": true
 },
 "empty-no-payouts": {
  "w": 427,
  "h": 327,
  "c": "empty-state",
  "alt": "No incentives yet",
  "svg": true
 },
 "empty-archive": {
  "w": 470,
  "h": 328,
  "c": "empty-state",
  "alt": "Archive is empty",
  "svg": true
 },
 "onboard-welcome": {
  "w": 457,
  "h": 412,
  "c": "onboarding",
  "alt": "Welcome / first sign-in",
  "svg": true
 },
 "onboard-link-author-id": {
  "w": 496,
  "h": 275,
  "c": "onboarding",
  "alt": "Link your Scopus / author ID",
  "svg": true
 },
 "onboard-complete-profile": {
  "w": 398,
  "h": 332,
  "c": "onboarding",
  "alt": "Complete your profile",
  "svg": true
 },
 "onboard-first-paper": {
  "w": 378,
  "h": 427,
  "c": "onboarding",
  "alt": "File your first paper (tip)",
  "svg": true
 },
 "onboard-invite-colleague": {
  "w": 512,
  "h": 312,
  "c": "onboarding",
  "alt": "Invite a colleague / co-author",
  "svg": true
 },
 "onboard-all-set": {
  "w": 471,
  "h": 423,
  "c": "onboarding",
  "alt": "Setup complete",
  "svg": true
 },
 "celebrate-first-publication": {
  "w": 339,
  "h": 365,
  "c": "celebration",
  "alt": "First publication moment",
  "svg": true
 },
 "celebrate-ten-papers": {
  "w": 376,
  "h": 437,
  "c": "celebration",
  "alt": "Paper-count milestone (5/10/25)",
  "svg": false
 },
 "celebrate-top-quartile": {
  "w": 361,
  "h": 372,
  "c": "celebration",
  "alt": "Q1 / top-quartile journal",
  "svg": true
 },
 "celebrate-first-citation": {
  "w": 340,
  "h": 356,
  "c": "celebration",
  "alt": "First citation",
  "svg": true
 },
 "celebrate-top-department": {
  "w": 403,
  "h": 420,
  "c": "celebration",
  "alt": "Department in the top ten",
  "svg": true
 },
 "celebrate-anniversary": {
  "w": 355,
  "h": 422,
  "c": "celebration",
  "alt": "Anniversary / thank-you",
  "svg": true
 },
 "badge-first-paper": {
  "w": 368,
  "h": 430,
  "c": "badge",
  "alt": "Badge FIRST_PAPER",
  "svg": true
 },
 "badge-first-q1": {
  "w": 368,
  "h": 430,
  "c": "badge",
  "alt": "Badge FIRST_Q1",
  "svg": true
 },
 "badge-papers-5": {
  "w": 371,
  "h": 432,
  "c": "badge",
  "alt": "Badge PAPERS_5",
  "svg": true
 },
 "badge-papers-10": {
  "w": 368,
  "h": 430,
  "c": "badge",
  "alt": "Badge PAPERS_10",
  "svg": true
 },
 "badge-papers-25": {
  "w": 367,
  "h": 431,
  "c": "badge",
  "alt": "Badge PAPERS_25",
  "svg": false
 },
 "badge-first-author": {
  "w": 367,
  "h": 431,
  "c": "badge",
  "alt": "Badge FIRST_AUTHOR",
  "svg": true
 },
 "badge-cross-department": {
  "w": 370,
  "h": 433,
  "c": "badge",
  "alt": "Badge CROSS_DEPARTMENT",
  "svg": true
 },
 "badge-quota-met": {
  "w": 369,
  "h": 433,
  "c": "badge",
  "alt": "Badge QUOTA_MET",
  "svg": true
 },
 "badge-top10-department": {
  "w": 370,
  "h": 433,
  "c": "badge",
  "alt": "Badge TOP10_DEPARTMENT",
  "svg": true
 },
 "badge-streak-3": {
  "w": 370,
  "h": 435,
  "c": "badge",
  "alt": "Badge STREAK_3",
  "svg": true
 },
 "badge-streak-6": {
  "w": 369,
  "h": 435,
  "c": "badge",
  "alt": "Badge STREAK_6",
  "svg": true
 },
 "badge-first-citation": {
  "w": 370,
  "h": 435,
  "c": "badge",
  "alt": "Badge FIRST_CITATION",
  "svg": true
 },
 "dept-cse": {
  "w": 437,
  "h": 288,
  "c": "department",
  "alt": "Department: CSE",
  "svg": true
 },
 "dept-ece": {
  "w": 337,
  "h": 392,
  "c": "department",
  "alt": "Department: ECE",
  "svg": true
 },
 "dept-eee": {
  "w": 395,
  "h": 302,
  "c": "department",
  "alt": "Department: EEE",
  "svg": true
 },
 "dept-mech": {
  "w": 391,
  "h": 349,
  "c": "department",
  "alt": "Department: MECH",
  "svg": true
 },
 "dept-auto": {
  "w": 398,
  "h": 321,
  "c": "department",
  "alt": "Department: AUTO (Automobile)",
  "svg": true
 },
 "dept-it": {
  "w": 371,
  "h": 388,
  "c": "department",
  "alt": "Department: IT",
  "svg": true
 },
 "dept-civil": {
  "w": 424,
  "h": 360,
  "c": "department",
  "alt": "Department: CIVIL",
  "svg": true
 },
 "dept-aids": {
  "w": 399,
  "h": 318,
  "c": "department",
  "alt": "Department: AI&DS",
  "svg": true
 },
 "dept-aiml": {
  "w": 381,
  "h": 354,
  "c": "department",
  "alt": "Department: AI&ML",
  "svg": true
 },
 "dept-bme": {
  "w": 427,
  "h": 311,
  "c": "department",
  "alt": "Department: BME",
  "svg": true
 },
 "dept-agri": {
  "w": 376,
  "h": 375,
  "c": "department",
  "alt": "Department: AGRI",
  "svg": true
 },
 "dept-mba": {
  "w": 426,
  "h": 280,
  "c": "department",
  "alt": "Department: MBA",
  "svg": true
 },
 "dept-sh-english": {
  "w": 456,
  "h": 314,
  "c": "department",
  "alt": "Department: S&H-ENGLISH",
  "svg": true
 },
 "dept-sh-chemistry": {
  "w": 411,
  "h": 364,
  "c": "department",
  "alt": "Department: S&H-CHY",
  "svg": true
 },
 "dept-sh-physics": {
  "w": 455,
  "h": 309,
  "c": "department",
  "alt": "Department: S&H-PHY",
  "svg": true
 },
 "dept-sh-maths": {
  "w": 415,
  "h": 356,
  "c": "department",
  "alt": "Department: S&H-MATHS",
  "svg": true
 },
 "dept-research-centre": {
  "w": 407,
  "h": 353,
  "c": "department",
  "alt": "Research centre (any non-teaching research unit)",
  "svg": true
 },
 "dept-interdisciplinary": {
  "w": 417,
  "h": 332,
  "c": "department",
  "alt": "Interdisciplinary / cross-department work",
  "svg": true
 },
 "topic-machine-learning": {
  "w": 359,
  "h": 384,
  "c": "topic",
  "alt": "Topic: machine learning",
  "svg": true
 },
 "topic-deep-learning": {
  "w": 351,
  "h": 357,
  "c": "topic",
  "alt": "Topic: deep learning",
  "svg": true
 },
 "topic-computer-vision": {
  "w": 383,
  "h": 334,
  "c": "topic",
  "alt": "Topic: computer vision / image processing",
  "svg": true
 },
 "topic-nlp": {
  "w": 383,
  "h": 312,
  "c": "topic",
  "alt": "Topic: natural language processing",
  "svg": true
 },
 "topic-iot": {
  "w": 405,
  "h": 378,
  "c": "topic",
  "alt": "Topic: Internet of Things",
  "svg": true
 },
 "topic-cybersecurity": {
  "w": 386,
  "h": 310,
  "c": "topic",
  "alt": "Topic: cybersecurity",
  "svg": true
 },
 "topic-blockchain": {
  "w": 429,
  "h": 207,
  "c": "topic",
  "alt": "Topic: blockchain",
  "svg": true
 },
 "topic-cloud-computing": {
  "w": 409,
  "h": 307,
  "c": "topic",
  "alt": "Topic: cloud computing",
  "svg": true
 },
 "topic-edge-computing": {
  "w": 390,
  "h": 426,
  "c": "topic",
  "alt": "Topic: edge / fog computing",
  "svg": true
 },
 "topic-big-data": {
  "w": 418,
  "h": 333,
  "c": "topic",
  "alt": "Topic: big data analytics",
  "svg": true
 },
 "topic-solar-energy": {
  "w": 412,
  "h": 394,
  "c": "topic",
  "alt": "Topic: solar / photovoltaics",
  "svg": true
 },
 "topic-wind-energy": {
  "w": 413,
  "h": 411,
  "c": "topic",
  "alt": "Topic: wind energy",
  "svg": true
 },
 "topic-power-electronics": {
  "w": 403,
  "h": 254,
  "c": "topic",
  "alt": "Topic: power electronics",
  "svg": true
 },
 "topic-electric-vehicles": {
  "w": 449,
  "h": 259,
  "c": "topic",
  "alt": "Topic: electric vehicles",
  "svg": true
 },
 "topic-smart-grid": {
  "w": 408,
  "h": 309,
  "c": "topic",
  "alt": "Topic: smart grid",
  "svg": true
 },
 "topic-wireless-5g": {
  "w": 372,
  "h": 381,
  "c": "topic",
  "alt": "Topic: wireless communication / 5G",
  "svg": true
 },
 "topic-antennas": {
  "w": 419,
  "h": 353,
  "c": "topic",
  "alt": "Topic: antennas and microwave",
  "svg": true
 },
 "topic-vlsi": {
  "w": 374,
  "h": 325,
  "c": "topic",
  "alt": "Topic: VLSI design",
  "svg": true
 },
 "topic-embedded-systems": {
  "w": 401,
  "h": 289,
  "c": "topic",
  "alt": "Topic: embedded systems",
  "svg": true
 },
 "topic-robotics": {
  "w": 398,
  "h": 337,
  "c": "topic",
  "alt": "Topic: robotics / automation",
  "svg": true
 },
 "topic-control-systems": {
  "w": 383,
  "h": 338,
  "c": "topic",
  "alt": "Topic: control systems",
  "svg": true
 },
 "topic-signal-processing": {
  "w": 459,
  "h": 238,
  "c": "topic",
  "alt": "Topic: signal processing",
  "svg": true
 },
 "topic-biomedical-imaging": {
  "w": 426,
  "h": 319,
  "c": "topic",
  "alt": "Topic: biomedical imaging",
  "svg": true
 },
 "topic-healthcare-ai": {
  "w": 385,
  "h": 317,
  "c": "topic",
  "alt": "Topic: healthcare AI / digital health",
  "svg": true
 },
 "topic-biomaterials": {
  "w": 429,
  "h": 287,
  "c": "topic",
  "alt": "Topic: biomaterials / tissue engineering",
  "svg": true
 },
 "topic-nanomaterials": {
  "w": 412,
  "h": 309,
  "c": "topic",
  "alt": "Topic: nanomaterials",
  "svg": true
 },
 "topic-composites": {
  "w": 401,
  "h": 302,
  "c": "topic",
  "alt": "Topic: composite materials",
  "svg": true
 },
 "topic-heat-transfer": {
  "w": 413,
  "h": 360,
  "c": "topic",
  "alt": "Topic: heat transfer / thermal engineering",
  "svg": true
 },
 "topic-cfd": {
  "w": 456,
  "h": 276,
  "c": "topic",
  "alt": "Topic: fluid dynamics / CFD",
  "svg": true
 },
 "topic-additive-manufacturing": {
  "w": 414,
  "h": 324,
  "c": "topic",
  "alt": "Topic: additive manufacturing / 3D printing",
  "svg": true
 },
 "topic-structural": {
  "w": 475,
  "h": 361,
  "c": "topic",
  "alt": "Topic: structural engineering",
  "svg": true
 },
 "topic-concrete": {
  "w": 463,
  "h": 317,
  "c": "topic",
  "alt": "Topic: concrete technology",
  "svg": true
 },
 "topic-water-resources": {
  "w": 474,
  "h": 357,
  "c": "topic",
  "alt": "Topic: water resources / hydraulics",
  "svg": true
 },
 "topic-environmental": {
  "w": 447,
  "h": 347,
  "c": "topic",
  "alt": "Topic: environmental engineering / sustainability",
  "svg": true
 },
 "topic-transportation": {
  "w": 472,
  "h": 320,
  "c": "topic",
  "alt": "Topic: transportation engineering",
  "svg": true
 },
 "topic-precision-agriculture": {
  "w": 476,
  "h": 355,
  "c": "topic",
  "alt": "Topic: precision agriculture / agri-tech",
  "svg": true
 },
 "topic-optimisation": {
  "w": 455,
  "h": 275,
  "c": "topic",
  "alt": "Topic: optimisation / operations research",
  "svg": true
 },
 "topic-quantum-computing": {
  "w": 381,
  "h": 369,
  "c": "topic",
  "alt": "Topic: quantum computing",
  "svg": true
 },
 "topic-computer-networks": {
  "w": 437,
  "h": 328,
  "c": "topic",
  "alt": "Topic: computer networks / SDN",
  "svg": true
 },
 "topic-edtech": {
  "w": 476,
  "h": 315,
  "c": "topic",
  "alt": "Topic: education technology / engineering education",
  "svg": true
 },
 "topic-food-technology": {
  "w": 429,
  "h": 329,
  "c": "topic",
  "alt": "Topic: food technology",
  "svg": true
 },
 "topic-industry-4": {
  "w": 475,
  "h": 340,
  "c": "topic",
  "alt": "Topic: Industry 4.0 / smart manufacturing",
  "svg": true
 },
 "icon-paper": {
  "w": 213,
  "h": 254,
  "c": "icon",
  "alt": "Icon: paper",
  "svg": true
 },
 "icon-journal": {
  "w": 225,
  "h": 254,
  "c": "icon",
  "alt": "Icon: journal",
  "svg": true
 },
 "icon-citation": {
  "w": 237,
  "h": 187,
  "c": "icon",
  "alt": "Icon: citation",
  "svg": true
 },
 "icon-quartile": {
  "w": 256,
  "h": 220,
  "c": "icon",
  "alt": "Icon: quartile ranking",
  "svg": true
 },
 "icon-doi": {
  "w": 207,
  "h": 256,
  "c": "icon",
  "alt": "Icon: DOI link",
  "svg": true
 },
 "icon-author": {
  "w": 216,
  "h": 239,
  "c": "icon",
  "alt": "Icon: author",
  "svg": true
 },
 "icon-coauthors": {
  "w": 256,
  "h": 197,
  "c": "icon",
  "alt": "Icon: co-authors",
  "svg": true
 },
 "icon-deadline": {
  "w": 256,
  "h": 234,
  "c": "icon",
  "alt": "Icon: deadline",
  "svg": true
 },
 "icon-payout": {
  "w": 256,
  "h": 242,
  "c": "icon",
  "alt": "Icon: payout",
  "svg": true
 },
 "icon-verified": {
  "w": 256,
  "h": 253,
  "c": "icon",
  "alt": "Icon: verified",
  "svg": true
 },
 "icon-flag": {
  "w": 222,
  "h": 256,
  "c": "icon",
  "alt": "Icon: flag",
  "svg": true
 },
 "icon-search": {
  "w": 237,
  "h": 241,
  "c": "icon",
  "alt": "Icon: search",
  "svg": true
 },
 "icon-scout": {
  "w": 247,
  "h": 256,
  "c": "icon",
  "alt": "Icon: research scout",
  "svg": true
 },
 "icon-idea": {
  "w": 256,
  "h": 233,
  "c": "icon",
  "alt": "Icon: idea",
  "svg": true
 },
 "icon-lab": {
  "w": 182,
  "h": 256,
  "c": "icon",
  "alt": "Icon: lab",
  "svg": true
 },
 "icon-conference": {
  "w": 221,
  "h": 256,
  "c": "icon",
  "alt": "Icon: conference",
  "svg": true
 },
 "icon-grant": {
  "w": 256,
  "h": 241,
  "c": "icon",
  "alt": "Icon: grant",
  "svg": true
 },
 "icon-calendar": {
  "w": 247,
  "h": 242,
  "c": "icon",
  "alt": "Icon: calendar",
  "svg": true
 },
 "icon-bell": {
  "w": 209,
  "h": 234,
  "c": "icon",
  "alt": "Icon: notifications",
  "svg": true
 },
 "icon-message": {
  "w": 234,
  "h": 220,
  "c": "icon",
  "alt": "Icon: message",
  "svg": true
 },
 "icon-discussion": {
  "w": 256,
  "h": 219,
  "c": "icon",
  "alt": "Icon: discussion",
  "svg": true
 },
 "icon-profile": {
  "w": 256,
  "h": 182,
  "c": "icon",
  "alt": "Icon: profile",
  "svg": true
 },
 "icon-department": {
  "w": 250,
  "h": 245,
  "c": "icon",
  "alt": "Icon: department",
  "svg": true
 },
 "icon-leaderboard": {
  "w": 256,
  "h": 155,
  "c": "icon",
  "alt": "Icon: leaderboard",
  "svg": true
 },
 "icon-badge": {
  "w": 211,
  "h": 242,
  "c": "icon",
  "alt": "Icon: badge",
  "svg": true
 },
 "icon-trophy": {
  "w": 256,
  "h": 228,
  "c": "icon",
  "alt": "Icon: trophy",
  "svg": true
 },
 "icon-upload": {
  "w": 227,
  "h": 211,
  "c": "icon",
  "alt": "Icon: upload",
  "svg": true
 },
 "icon-download": {
  "w": 227,
  "h": 212,
  "c": "icon",
  "alt": "Icon: download",
  "svg": true
 },
 "icon-import": {
  "w": 256,
  "h": 245,
  "c": "icon",
  "alt": "Icon: import",
  "svg": true
 },
 "icon-export": {
  "w": 248,
  "h": 256,
  "c": "icon",
  "alt": "Icon: export",
  "svg": true
 },
 "icon-archive": {
  "w": 252,
  "h": 201,
  "c": "icon",
  "alt": "Icon: archive",
  "svg": true
 },
 "icon-audit": {
  "w": 256,
  "h": 227,
  "c": "icon",
  "alt": "Icon: audit",
  "svg": true
 },
 "icon-report": {
  "w": 209,
  "h": 252,
  "c": "icon",
  "alt": "Icon: report",
  "svg": true
 },
 "icon-settings": {
  "w": 251,
  "h": 246,
  "c": "icon",
  "alt": "Icon: settings",
  "svg": true
 },
 "icon-privacy": {
  "w": 204,
  "h": 255,
  "c": "icon",
  "alt": "Icon: privacy",
  "svg": true
 },
 "icon-approve": {
  "w": 215,
  "h": 238,
  "c": "icon",
  "alt": "Icon: approve",
  "svg": true
 },
 "icon-reject": {
  "w": 240,
  "h": 239,
  "c": "icon",
  "alt": "Icon: reject / returned",
  "svg": true
 },
 "icon-pending": {
  "w": 197,
  "h": 241,
  "c": "icon",
  "alt": "Icon: pending",
  "svg": true
 },
 "icon-edit": {
  "w": 234,
  "h": 238,
  "c": "icon",
  "alt": "Icon: edit",
  "svg": true
 },
 "icon-delete": {
  "w": 229,
  "h": 239,
  "c": "icon",
  "alt": "Icon: delete",
  "svg": true
 },
 "icon-filter": {
  "w": 244,
  "h": 225,
  "c": "icon",
  "alt": "Icon: filter",
  "svg": true
 },
 "icon-sort": {
  "w": 243,
  "h": 185,
  "c": "icon",
  "alt": "Icon: sort",
  "svg": true
 },
 "icon-share": {
  "w": 234,
  "h": 247,
  "c": "icon",
  "alt": "Icon: share",
  "svg": true
 },
 "icon-bookmark": {
  "w": 197,
  "h": 231,
  "c": "icon",
  "alt": "Icon: bookmark / save",
  "svg": true
 },
 "icon-favourite": {
  "w": 241,
  "h": 231,
  "c": "icon",
  "alt": "Icon: favourite",
  "svg": true
 },
 "icon-like": {
  "w": 241,
  "h": 214,
  "c": "icon",
  "alt": "Icon: like",
  "svg": true
 },
 "icon-comment": {
  "w": 243,
  "h": 214,
  "c": "icon",
  "alt": "Icon: comment",
  "svg": true
 },
 "icon-attachment": {
  "w": 236,
  "h": 237,
  "c": "icon",
  "alt": "Icon: attachment",
  "svg": true
 },
 "icon-email": {
  "w": 256,
  "h": 181,
  "c": "icon",
  "alt": "Icon: email",
  "svg": true
 },
 "icon-globe": {
  "w": 256,
  "h": 256,
  "c": "icon",
  "alt": "Icon: web / international",
  "svg": true
 },
 "icon-open-access": {
  "w": 207,
  "h": 256,
  "c": "icon",
  "alt": "Icon: open access",
  "svg": true
 },
 "icon-impact": {
  "w": 256,
  "h": 217,
  "c": "icon",
  "alt": "Icon: impact / growth",
  "svg": true
 },
 "icon-h-index": {
  "w": 256,
  "h": 198,
  "c": "icon",
  "alt": "Icon: h-index",
  "svg": true
 },
 "icon-patent": {
  "w": 256,
  "h": 218,
  "c": "icon",
  "alt": "Icon: patent",
  "svg": true
 },
 "icon-book-chapter": {
  "w": 256,
  "h": 179,
  "c": "icon",
  "alt": "Icon: book chapter",
  "svg": true
 },
 "icon-thesis": {
  "w": 256,
  "h": 201,
  "c": "icon",
  "alt": "Icon: thesis / student",
  "svg": true
 },
 "icon-mentor": {
  "w": 256,
  "h": 226,
  "c": "icon",
  "alt": "Icon: mentor",
  "svg": true
 },
 "icon-agreement": {
  "w": 256,
  "h": 170,
  "c": "icon",
  "alt": "Icon: agreement / MoU",
  "svg": true
 },
 "icon-home": {
  "w": 256,
  "h": 236,
  "c": "icon",
  "alt": "Icon: home",
  "svg": true
 },
 "icon-highlights": {
  "w": 256,
  "h": 220,
  "c": "icon",
  "alt": "Icon: new / highlights",
  "svg": true
 },
 "deco-divider-leaf": {
  "w": 476,
  "h": 117,
  "c": "decorative",
  "alt": "Section divider with leaf sprig",
  "svg": true
 },
 "deco-corner-laurel": {
  "w": 329,
  "h": 379,
  "c": "decorative",
  "alt": "Corner flourish (laurel)",
  "svg": true
 },
 "deco-sparkles": {
  "w": 244,
  "h": 245,
  "c": "decorative",
  "alt": "Heading accent sparkles",
  "svg": true
 },
 "deco-divider-dots": {
  "w": 467,
  "h": 98,
  "c": "decorative",
  "alt": "Dotted divider with star",
  "svg": true
 },
 "deco-scatter-leaves-books": {
  "w": 391,
  "h": 390,
  "c": "decorative",
  "alt": "Scatter cluster of leaves, dots and books (not a seamless tile)",
  "svg": true
 },
 "deco-underline-swoosh": {
  "w": 446,
  "h": 101,
  "c": "decorative",
  "alt": "Hand-drawn clay underline for a heading word",
  "svg": true
 },
 "banner-home-faculty": {
  "w": 1600,
  "h": 173,
  "c": "banner",
  "alt": "Wide page-header strip (~9:1), title space on the left",
  "svg": false
 },
 "banner-discover": {
  "w": 1600,
  "h": 168,
  "c": "banner",
  "alt": "Wide page-header strip (~9:1)",
  "svg": false
 },
 "banner-leaderboard": {
  "w": 1600,
  "h": 173,
  "c": "banner",
  "alt": "Wide page-header strip (~9:1)",
  "svg": false
 },
 "banner-file-paper": {
  "w": 1600,
  "h": 172,
  "c": "banner",
  "alt": "Wide page-header strip (~9:1)",
  "svg": false
 },
 "banner-calendar": {
  "w": 1600,
  "h": 168,
  "c": "banner",
  "alt": "Wide page-header strip (~9:1)",
  "svg": false
 },
 "banner-messages": {
  "w": 1600,
  "h": 174,
  "c": "banner",
  "alt": "Wide page-header strip (~9:1)",
  "svg": false
 }
} as const satisfies Record<string, IllustrationMeta>
export type IllustrationName = keyof typeof ILLUSTRATIONS
