# Generated by Django 5.2.16 on 2026-07-30 02:19

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyMaster',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, max_length=128, null=True)),
                ('biometric_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('staff_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('scopus_author_id', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('raw_json', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SnipSource',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('source_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('title', models.CharField(max_length=512)),
                ('print_issn', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('e_issn', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('snip', models.FloatField(blank=True, null=True)),
                ('sjr', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField(db_index=True, default=2025)),
                ('raw_json', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='claim',
            name='affiliation_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='biometric_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='designation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='impact_factor',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='indexing_level',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='indexing_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='is_student_publication',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='linkage_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='payout_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='proof_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='publication_date',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='publication_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='qf_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='scopus_author_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='scopus_author_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='sec_proof_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='sec_refs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='self_reported_quartile',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='staff_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='status_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='yukthi_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='formulaconfig',
            name='qf_others',
            field=models.FloatField(default=4000),
        ),
        migrations.AddField(
            model_name='user',
            name='biometric_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='scopus_author_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='scopus_author_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='quartile',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='PaidLedger',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('payout_month', models.DateField(db_index=True)),
                ('department', models.CharField(blank=True, max_length=128, null=True)),
                ('faculty_name', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_id', models.CharField(blank=True, max_length=64, null=True)),
                ('biometric_id', models.CharField(blank=True, max_length=64, null=True)),
                ('paper_title', models.TextField(blank=True, null=True)),
                ('journal_title', models.CharField(blank=True, max_length=512, null=True)),
                ('amount', models.FloatField(default=0)),
                ('voucher_number', models.CharField(blank=True, max_length=64, null=True)),
                ('raw_json', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_rows', to='core.claim')),
            ],
        ),
    ]
