# Generated by Django 5.2.16 on 2026-07-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ticket_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaconfig',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulaconfig',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulaconfig',
            name='name',
            field=models.CharField(default='Policy v1', max_length=128),
        ),
        migrations.AddField(
            model_name='formulaconfig',
            name='publication_type_multipliers_json',
            field=models.TextField(default='{"Journal":1,"Conference Proceeding":1,"Book Series":1,"Other":1}'),
        ),
        migrations.AddField(
            model_name='formulaconfig',
            name='qf_only_for_no_snip',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulaconfig',
            name='snip_cap',
            field=models.FloatField(default=30),
        ),
        migrations.AddField(
            model_name='formulaconfig',
            name='student_remuneration_zero',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulaconfig',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
