# Generated by Django 5.2.17 on 2026-08-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_policy_versioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='indexing_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
