# Generated by Django 5.2.17 on 2026-08-12 15:01

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_claim_indexing_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claim_reason',
            field=models.CharField(choices=[('INCENTIVE', 'Faculty Publication Incentive'), ('COUNT_ONLY', 'Publication count only')], default='INCENTIVE', max_length=32),
        ),
        migrations.AddField(
            model_name='claim',
            name='reference_articles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClaimAttachment',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('PUBLISHED_PAPER', 'Full-length published paper'), ('SEC_REFERENCE', 'Cited reference with SEC affiliation')], max_length=32)),
                ('url', models.TextField()),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('size_bytes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.claim')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['claim', 'kind'], name='core_claima_claim_i_111061_idx')],
            },
        ),
    ]
