# Generated by Django 5.2.17 on 2026-08-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_claim_reason_and_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CLEARED', 'Cleared'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('HOD_APPROVED', 'Hod Approved'), ('PRINCIPAL_APPROVED', 'Principal Approved'), ('RESEARCH_APPROVED', 'Research Approved'), ('FINANCE_APPROVED', 'Finance Approved')], default='DRAFT', max_length=32),
        ),
        migrations.AlterField(
            model_name='claimaction',
            name='from_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CLEARED', 'Cleared'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('HOD_APPROVED', 'Hod Approved'), ('PRINCIPAL_APPROVED', 'Principal Approved'), ('RESEARCH_APPROVED', 'Research Approved'), ('FINANCE_APPROVED', 'Finance Approved')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='claimaction',
            name='to_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CLEARED', 'Cleared'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('HOD_APPROVED', 'Hod Approved'), ('PRINCIPAL_APPROVED', 'Principal Approved'), ('RESEARCH_APPROVED', 'Research Approved'), ('FINANCE_APPROVED', 'Finance Approved')], max_length=32, null=True),
        ),
    ]
