# Generated by Django 5.2.17 on 2026-08-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_claim_status_alter_claimaction_from_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimattachment',
            name='ref_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='claimattachment',
            name='ref_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
