# Generated by Django 5.2.17 on 2026-08-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_claimattachment_ref_number_claimattachment_ref_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='au_annexure_ref',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='ugc_care_ref',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='affiliation_ok',
            field=models.BooleanField(default=False),
        ),
    ]
