# Generated by Django 5.2.17 on 2026-08-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_claim_au_annexure_ref_claim_ugc_care_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='remuneration_category',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='remuneration_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulaconfig',
            name='fixed_journal_no_snip',
            field=models.FloatField(default=5000),
        ),
        migrations.AddField(
            model_name='formulaconfig',
            name='fixed_other_no_snip',
            field=models.FloatField(default=4000),
        ),
        migrations.AddField(
            model_name='formulaconfig',
            name='fixed_web_of_science',
            field=models.FloatField(default=5000),
        ),
        migrations.AddField(
            model_name='formulaconfig',
            name='max_authors',
            field=models.PositiveIntegerField(default=9),
        ),
        migrations.AddField(
            model_name='formulaconfig',
            name='min_sec_references',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='formulaconfig',
            name='qf_q4',
            field=models.FloatField(default=7000),
        ),
    ]
