# Generated by Django 5.2.17 on 2026-08-15 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_claim_remuneration_category_claim_remuneration_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='cleared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claim',
            name='manual_verification_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='manual_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='manual_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claim',
            name='normalized_title',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='quartile_source',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='second_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='second_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claim',
            name='self_reported_snip',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='snip_source',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='formulaconfig',
            name='high_value_threshold',
            field=models.FloatField(default=100000),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status', '-updated_at'], name='core_claim_status_18260e_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['owner', 'status'], name='core_claim_owner_i_fa98d9_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['payout_month'], name='core_claim_payout__4fe5f0_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['-submitted_at'], name='core_claim_submitt_2cf2a9_idx'),
        ),
    ]
