# Generated by Django 5.2.17 on 2026-08-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_backfill_trust_boundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybatch',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
