# Generated by Django 5.2.17 on 2026-08-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_fix_admin_notification_hrefs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaconfig',
            name='high_value_threshold',
            field=models.FloatField(default=0),
        ),
    ]
