# Generated by Django 5.2.17 on 2026-08-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_claim_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimattachment',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
