# Generated by Django 5.2.17 on 2026-08-18 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_attachment_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='override_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_overrides', to=settings.AUTH_USER_MODEL),
        ),
    ]
