# Generated by Django 5.2.17 on 2026-08-18 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_duplicate_override_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='principal_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='principal_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CLEARED', 'Cleared'), ('PRINCIPAL_APPROVED', 'Principal Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('HOD_APPROVED', 'Hod Approved'), ('RESEARCH_APPROVED', 'Research Approved'), ('FINANCE_APPROVED', 'Finance Approved')], default='DRAFT', max_length=32),
        ),
        migrations.AlterField(
            model_name='claimaction',
            name='from_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CLEARED', 'Cleared'), ('PRINCIPAL_APPROVED', 'Principal Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('HOD_APPROVED', 'Hod Approved'), ('RESEARCH_APPROVED', 'Research Approved'), ('FINANCE_APPROVED', 'Finance Approved')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='claimaction',
            name='to_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CLEARED', 'Cleared'), ('PRINCIPAL_APPROVED', 'Principal Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('HOD_APPROVED', 'Hod Approved'), ('RESEARCH_APPROVED', 'Research Approved'), ('FINANCE_APPROVED', 'Finance Approved')], max_length=32, null=True),
        ),
    ]
