# Generated by Django 5.2.17 on 2026-08-19 14:49

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_principal_approval_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalStanding',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('SCOPUS_DISCONTINUED', 'Scopus discontinued list'), ('UGC_CARE', 'UGC-CARE list')], db_index=True, max_length=32)),
                ('issn', models.CharField(db_index=True, max_length=32)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('listed', models.BooleanField(default=True)),
                ('changed_on', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['issn', 'listed'], name='core_journa_issn_dd9e16_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'issn'), name='one_standing_per_source_and_issn')],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('financial_year', models.CharField(db_index=True, max_length=9)),
                ('department', models.CharField(blank=True, max_length=128, null=True)),
                ('amount', models.FloatField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-financial_year', 'department'],
                'constraints': [models.UniqueConstraint(fields=('financial_year', 'department'), name='one_budget_per_slice')],
            },
        ),
        migrations.CreateModel(
            name='DuplicateFinding',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('SAME_PERSON', 'Same person paid more than once'), ('CROSS_PERSON', 'Paid to more than one person')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('OPEN', 'Not yet reviewed'), ('CONFIRMED', 'A real duplicate'), ('DISMISSED', 'Not a duplicate'), ('RECOVERED', 'Recovered')], db_index=True, default='OPEN', max_length=16)),
                ('match_key', models.CharField(db_index=True, max_length=512)),
                ('matched_on', models.CharField(default='title', max_length=16)),
                ('paper_title', models.TextField(blank=True, null=True)),
                ('faculty_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rows_json', models.TextField()),
                ('payment_count', models.PositiveIntegerField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('extra_amount', models.FloatField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('recovered_amount', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-extra_amount'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'match_key', 'faculty_name'), name='one_finding_per_group')],
            },
        ),
    ]
