# Generated by Django 5.2.17 on 2026-08-25 07:32

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_profile_change_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchInterest',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['domain'],
                'indexes': [models.Index(fields=['domain'], name='core_resear_domain_2f0370_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'domain'), name='unique_interest_per_person')],
            },
        ),
    ]
