# Generated by Django 5.2.17 on 2026-08-26 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_repair_scimago_issns'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='director_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='director_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CLEARED', 'Cleared'), ('PRINCIPAL_APPROVED', 'Principal Approved'), ('DIRECTOR_APPROVED', 'Director Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('HOD_APPROVED', 'Hod Approved'), ('RESEARCH_APPROVED', 'Research Approved'), ('FINANCE_APPROVED', 'Finance Approved')], default='DRAFT', max_length=32),
        ),
        migrations.AlterField(
            model_name='claimaction',
            name='from_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CLEARED', 'Cleared'), ('PRINCIPAL_APPROVED', 'Principal Approved'), ('DIRECTOR_APPROVED', 'Director Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('HOD_APPROVED', 'Hod Approved'), ('RESEARCH_APPROVED', 'Research Approved'), ('FINANCE_APPROVED', 'Finance Approved')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='claimaction',
            name='to_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CLEARED', 'Cleared'), ('PRINCIPAL_APPROVED', 'Principal Approved'), ('DIRECTOR_APPROVED', 'Director Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('HOD_APPROVED', 'Hod Approved'), ('RESEARCH_APPROVED', 'Research Approved'), ('FINANCE_APPROVED', 'Finance Approved')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FACULTY', 'Faculty'), ('HOD', 'Hod'), ('PRINCIPAL', 'Principal'), ('DIRECTOR', 'Director'), ('RESEARCH_CELL', 'Research Cell'), ('FINANCE', 'Finance'), ('SUPER_ADMIN', 'Super Admin')], default='FACULTY', max_length=32),
        ),
    ]
