# Generated by Django 5.2.17 on 2026-08-26 04:18

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_director_approval_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentTarget',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('department', models.CharField(db_index=True, max_length=255)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('metric', models.CharField(choices=[('PUBLICATIONS', 'Publications'), ('Q1', 'Q1 publications'), ('FIRST_AUTHOR', 'Papers led from this department')], max_length=24)),
                ('target', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets_set_on_them', to=settings.AUTH_USER_MODEL)),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targets_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'department', 'metric'],
                'constraints': [models.UniqueConstraint(fields=('department', 'year', 'metric', 'person'), name='one_target_per_metric_per_person_per_year'), models.UniqueConstraint(condition=models.Q(('person__isnull', True)), fields=('department', 'year', 'metric'), name='one_department_target_per_metric_per_year')],
            },
        ),
    ]
