# Generated by Django 5.2.17 on 2026-08-26 07:40

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_department_targets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Everybody'), ('DEPARTMENT', 'One department'), ('OFFICE', 'The office, and whoever asked')], db_index=True, default='PUBLIC', max_length=16)),
                ('department', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('topic', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('journal_title', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_post_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('post_count', models.PositiveIntegerField(default=0)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='core.claim')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads_started', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_post_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('HUMAN', 'Written by a person'), ('AGENT', 'Answered by the assistant'), ('SYSTEM', 'Recorded by the system')], default='HUMAN', max_length=8)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_deleted', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='core.post')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.thread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('kind', models.CharField(choices=[('PAYOUT_RUN', 'Payout run'), ('SUBMISSION_WINDOW', 'Submission window'), ('DEADLINE', 'Deadline'), ('MEETING', 'Meeting'), ('OTHER', 'Something else')], db_index=True, default='OTHER', max_length=24)),
                ('starts_on', models.DateField(db_index=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Everybody'), ('DEPARTMENT', 'One department'), ('OFFICE', 'The office, and whoever asked')], db_index=True, default='PUBLIC', max_length=16)),
                ('department', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.claim')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.thread')),
            ],
            options={
                'ordering': ['starts_on', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ThreadSubscription',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('muted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('USER', 'A person'), ('JOURNAL', 'A journal'), ('PAPER', 'A paper'), ('DEPARTMENT', 'A department'), ('AGENT', 'The assistant')], db_index=True, max_length=16)),
                ('label', models.CharField(max_length=300)),
                ('journal_title', models.CharField(blank=True, max_length=512, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentioned_in', to='core.claim')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentioned_in', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='core.post')),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'user'], name='core_mentio_kind_8a4613_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['visibility', '-last_post_at'], name='core_thread_visibil_fd498b_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['department', '-last_post_at'], name='core_thread_departm_426ba9_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['thread', 'created_at'], name='core_post_thread__82e2f9_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['starts_on', 'visibility'], name='core_calend_starts__753961_idx'),
        ),
        migrations.AddConstraint(
            model_name='threadsubscription',
            constraint=models.UniqueConstraint(fields=('thread', 'user'), name='one_subscription_per_thread'),
        ),
    ]
