# Generated by Django 5.2.17 on 2026-08-26 11:02

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_discussions_and_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='quota_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='quota_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty_type',
            field=models.CharField(choices=[('REGULAR', 'Regular faculty'), ('RESEARCH', 'Research faculty')], db_index=True, default='REGULAR', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='research_quota',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='research_quota_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_reason',
            field=models.CharField(choices=[('INCENTIVE', 'Faculty Publication Incentive'), ('COUNT_ONLY', 'Publication count only'), ('STUDENT_PROJECT', 'Student project conference incentive')], default='INCENTIVE', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FACULTY', 'Faculty'), ('HOD', 'Hod'), ('PRINCIPAL', 'Principal'), ('DIRECTOR', 'Director'), ('RESEARCH_COORDINATOR', 'Research Coordinator'), ('RESEARCH_CELL', 'Research Cell'), ('FINANCE', 'Finance'), ('SUPER_ADMIN', 'Super Admin')], default='FACULTY', max_length=32),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('department', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=9, null=True)),
                ('mentor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_created', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_mentored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='core.team'),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('register_number', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('programme', models.CharField(blank=True, max_length=128, null=True)),
                ('year_of_study', models.CharField(blank=True, max_length=32, null=True)),
                ('mentor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.team')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('register_number__isnull', False)), fields=('team', 'register_number'), name='one_row_per_student_per_team')],
            },
        ),
    ]
