# Generated by Django 5.2.17 on 2026-08-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_research_faculty_and_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='quota_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
