# Generated by Django 5.2.17 on 2026-08-27 03:57

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_repair_multi_zero_issns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Everybody'), ('DEPARTMENT', 'One department'), ('OFFICE', 'The office, and whoever asked'), ('DIRECT', 'The people in it')], db_index=True, default='PUBLIC', max_length=16),
        ),
        migrations.CreateModel(
            name='ThreadParticipant',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('thread', 'user'), name='one_row_per_person_per_thread')],
            },
        ),
    ]
