# Generated by Django 5.2.17 on 2026-08-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    """One research-quota slot, one paper.

    The position was handed out as MAX(quota_position) + 1 in a statement of
    its own, with no lock and nothing in the schema to catch a collision, so
    two submits for the same author and year that interleaved could both be
    given the same number.

    Checked against the live database before adding it: of 3,236 claims, none
    carries a `quota_position` at all -- the column is only ever written for
    research faculty and there are none on file yet -- so no existing row can
    violate the constraint and no data repair is needed here. NULLs are
    distinct under a unique constraint on both SQLite and PostgreSQL, so the
    3,236 rows with no position stay legal however many of them there are.
    """

    dependencies = [
        ('core', '0035_direct_threads'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.UniqueConstraint(fields=('owner', 'publication_year', 'quota_position'), name='uniq_claim_quota_slot_per_owner_year'),
        ),
    ]
