# Generated by Django 5.2.17 on 2026-09-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_claim_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='rejected_outright',
            field=models.BooleanField(default=False),
        ),
    ]
