# Generated by Django 5.2.17 on 2026-09-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_team_roster_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaconfig',
            name='student_project_amount',
            field=models.FloatField(default=15000),
        ),
    ]
