# Generated by Django 5.2.17 on 2026-09-23 11:27
#
# Two tables -- discrepancy flags and per-file content checks -- and one data
# step: flag the imported paid claims whose amount or status does not add up
# (core.services.import_discrepancies). A migration rather than a manual
# command because the Render deployment has no shell to run one from; the
# same function backs `manage.py flag_import_discrepancies`, and it is
# idempotent, so running both is harmless.

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def flag_existing_import_discrepancies(apps, schema_editor):
    from core.services.import_discrepancies import flag_import_discrepancies

    flag_import_discrepancies(apps)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_account_self_service_and_google_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentCheck',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('kind', models.CharField(choices=[('PUBLISHED_PAPER', 'Full-length published paper'), ('SEC_REFERENCE', 'Cited reference with SEC affiliation')], max_length=32)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('claim_fingerprint', models.CharField(blank=True, max_length=64, null=True)),
                ('outcome', models.CharField(choices=[('MATCHED', 'The file says what the claim says'), ('MISMATCH', 'The title or DOI is not in the file'), ('NO_TEXT', 'No text to read -- probably scanned'), ('UNREADABLE', 'The file could not be opened')], max_length=16)),
                ('found_json', models.TextField(default='[]')),
                ('missing_json', models.TextField(default='[]')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('text_chars', models.PositiveIntegerField(default=0)),
                ('checked_at', models.DateTimeField()),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_checks', to='core.claim')),
            ],
            options={
                'ordering': ['checked_at'],
                'constraints': [models.UniqueConstraint(fields=('claim', 'url'), name='one_check_per_claim_file')],
            },
        ),
        migrations.CreateModel(
            name='ClaimFlag',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('CONTENT_MISMATCH', 'The file does not match the claim'), ('AMOUNT', 'Amount'), ('AUTHOR', 'Author'), ('AFFILIATION', 'Affiliation'), ('DUPLICATE', 'Possible duplicate'), ('OTHER', 'Something else')], db_index=True, max_length=32)),
                ('source', models.CharField(choices=[('AUTO', 'Raised by a check'), ('MANUAL', 'Raised by a reviewer')], default='MANUAL', max_length=8)),
                ('note', models.TextField()),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('auto_key', models.CharField(blank=True, max_length=255, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='core.claim')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_raised', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-raised_at'],
                'indexes': [models.Index(fields=['claim', 'resolved_at'], name='core_claimf_claim_i_2b6a35_idx')],
                'constraints': [models.UniqueConstraint(fields=('claim', 'auto_key'), name='one_auto_flag_per_key')],
            },
        ),
        migrations.RunPython(flag_existing_import_discrepancies, migrations.RunPython.noop),
    ]
