# Generated by Django 5.2.17 on 2026-09-23 08:18

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_student_project_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopusProfile',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('scopus_id', models.CharField(max_length=64, unique=True)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=512, null=True)),
                ('total_publications', models.PositiveIntegerField(blank=True, null=True)),
                ('total_citations', models.PositiveIntegerField(blank=True, null=True)),
                ('h_index', models.PositiveIntegerField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('source_sheet', models.CharField(blank=True, default='', max_length=255)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('imported_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scopus_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['author_name', 'scopus_id'],
            },
        ),
    ]
