# Generated by Django 5.2.17 on 2026-09-24 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_social_feed'),
        ('core', '0047_hook_rewards'),
    ]

    operations = [
    ]
