# Generated by Django 5.2.17 on 2026-09-24 02:52
# Follows the base branch's leaf (0049) after complete-frontend2 was merged in; renumber again if another branch lands first.

import core.models
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def backfill_last_read(apps, schema_editor):
    """Give every existing participant a read mark, so the unread counts start honest.

    Without one, `api/dm._unread` counts every message the other person ever
    sent as unread, and on the day this ships every Messages badge lights up
    for conversations read long ago. Where the old thread page recorded when
    the person last opened it (`ThreadSubscription.last_read_at`) that is used;
    otherwise the conversation is taken as read up to now.
    """
    from django.utils import timezone

    ThreadParticipant = apps.get_model("core", "ThreadParticipant")
    ThreadSubscription = apps.get_model("core", "ThreadSubscription")
    read = {
        (s.thread_id, s.user_id): s.last_read_at
        for s in ThreadSubscription.objects.filter(last_read_at__isnull=False)
    }
    now = timezone.now()
    for p in ThreadParticipant.objects.filter(last_read_at__isnull=True):
        p.last_read_at = read.get((p.thread_id, p.user_id), now)
        p.save(update_fields=["last_read_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_repair_ledger_and_record_duplicates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=200)),
                ('journal', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=200)),
                ('journal', models.CharField(blank=True, default='', max_length=512)),
                ('message', models.TextField(blank=True, default='')),
                ('state', models.CharField(choices=[('PENDING', 'Waiting for an answer'), ('CALL', 'A call was suggested'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=16)),
                ('response_note', models.CharField(blank=True, default='', max_length=500)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PinnedPaper',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileVisit',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SocialSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='social_settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('muted_json', models.TextField(default='[]')),
                ('count_my_visits', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='feedreaction',
            name='one_like_per_person_per_post',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='follow_one_thing',
        ),
        migrations.AddField(
            model_name='feedreaction',
            name='kind',
            field=models.CharField(choices=[('LIKE', 'Like'), ('CONGRATS', 'Congrats'), ('INTERESTED', 'Interested'), ('COLLABORATE', 'Want to collaborate')], default='LIKE', max_length=16),
        ),
        migrations.AddField(
            model_name='follow',
            name='journal',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='follow',
            name='topic',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='threadparticipant',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='feedreaction',
            constraint=models.UniqueConstraint(fields=('post', 'user', 'kind'), name='one_reaction_kind_per_person_per_post'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(condition=models.Q(('topic__isnull', False)), fields=('follower', 'topic'), name='follow_a_topic_once'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(condition=models.Q(('journal__isnull', False)), fields=('follower', 'journal'), name='follow_a_journal_once'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('department__isnull', True), ('journal__isnull', True), ('person__isnull', False), ('topic__isnull', True)), models.Q(('department__isnull', False), ('journal__isnull', True), ('person__isnull', True), ('topic__isnull', True)), models.Q(('department__isnull', True), ('journal__isnull', True), ('person__isnull', True), ('topic__isnull', False)), models.Q(('department__isnull', True), ('journal__isnull', False), ('person__isnull', True), ('topic__isnull', True)), _connector='OR'), name='follow_one_thing'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='members',
            field=models.ManyToManyField(related_name='collaborations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collab_request', to='core.post'),
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_requests_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_requests', to='core.thread'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaboration', to='core.collaborationrequest'),
        ),
        migrations.AddField(
            model_name='endorsement',
            name='endorser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pinnedpaper',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='core.claim'),
        ),
        migrations.AddField(
            model_name='pinnedpaper',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_papers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='core.feedpost'),
        ),
        migrations.AddField(
            model_name='postview',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_seen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilevisit',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilevisit',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles_visited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='endorsement',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='core.skill'),
        ),
        migrations.AddConstraint(
            model_name='pinnedpaper',
            constraint=models.UniqueConstraint(fields=('user', 'claim'), name='pin_a_paper_once'),
        ),
        migrations.AddConstraint(
            model_name='postview',
            constraint=models.UniqueConstraint(fields=('post', 'viewer'), name='one_view_per_person_per_post'),
        ),
        migrations.AddIndex(
            model_name='profilevisit',
            index=models.Index(fields=['profile', 'day'], name='visit_by_profile_day'),
        ),
        migrations.AddConstraint(
            model_name='profilevisit',
            constraint=models.UniqueConstraint(fields=('profile', 'viewer', 'day'), name='one_visit_per_viewer_per_day'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['name'], name='skill_by_name'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), name='one_skill_per_name_per_person'),
        ),
        migrations.AddConstraint(
            model_name='endorsement',
            constraint=models.UniqueConstraint(fields=('skill', 'endorser'), name='endorse_a_skill_once'),
        ),
        migrations.RunPython(backfill_last_read, migrations.RunPython.noop),
    ]
