# Generated by Django 5.2.17 on 2026-09-24 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_notification_hooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='ends_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='starts_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Everybody'), ('DEPARTMENT', 'One department'), ('OFFICE', 'The office, and whoever asked'), ('PRIVATE', 'Only me')], db_index=True, default='PUBLIC', max_length=16),
        ),
        migrations.CreateModel(
            name='CalendarFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_feed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
