# Generated by Django 5.2.17 on 2026-09-24 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_calendar_events'),
        ('core', '0052_publication_record'),
    ]

    operations = [
    ]
