# Generated by Django 5.2.17 on 2026-09-24 13:54

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_merge_0052_calendar_events_0052_publication_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimConfirmation',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('condition_id', models.CharField(max_length=32)),
                ('text_version', models.CharField(max_length=16)),
                ('text', models.TextField()),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('paper_title', models.TextField(blank=True, null=True)),
                ('ticked_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='core.claim')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_confirmations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['claim', 'recorded_at'], name='core_claimc_claim_i_c144b5_idx')],
            },
        ),
    ]
