# Generated by Django 5.2.17 on 2026-09-24 14:30

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_claim_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WallCheer',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('paper_key', models.CharField(db_index=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wall_cheers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('paper_key', 'user'), name='one_cheer_per_person_paper')],
            },
        ),
    ]
