# Generated by Django 5.2.17 on 2026-09-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_claim_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='mentor_staff_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
