# Generated by Django 5.2.17 on 2026-09-28 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_wall_cheer'),
        ('core', '0057_scopus_profile'),
    ]

    operations = [
    ]
