# Generated by Django 5.2.17 on 2026-09-28 05:55

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_merge_0055_wall_cheer_0057_scopus_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorAlias',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name_key', models.CharField(max_length=160, unique=True)),
                ('sample_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('NOT_ROSTER', 'Not on our roster'), ('AMBIGUOUS', 'Ambiguous')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_aliases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
