# Generated by Django 5.2.17 on 2026-09-28 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_discover_dismissal'),
        ('core', '0059_thread_context'),
    ]

    operations = [
    ]
