# Generated by Django 5.2.17 on 2026-09-28 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_author_alias'),
        ('core', '0060_merge_0059_discover_dismissal_0059_thread_context'),
    ]

    operations = [
    ]
