# Generated by Django 5.2.17 on 2026-09-28 07:24

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_merge_20260928_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutRun',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='QUEUED', max_length=16)),
                ('result_json', models.TextField(blank=True, default='')),
                ('usage_json', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('error_code', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scout_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
