# Generated by Django 5.2.17 on 2026-09-28 07:27

from django.db import migrations, models

PLACEHOLDERS = ["-", "--", "—", "–", "n/a", "na", "n.a", "n.a.", "nil", "none", "null", "nan", "unknown", "0"]


def blank_placeholder_venues(apps, schema_editor):
    Publication = apps.get_model("core", "Publication")
    for p in Publication.objects.exclude(venue="").only("id", "venue").iterator():
        if p.venue.strip().lower() in PLACEHOLDERS:
            Publication.objects.filter(id=p.id).update(venue="")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_merge_20260928_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='scopus_citations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='scopus_indexed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='scopus_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ImpactShare',
        ),
        migrations.RunPython(blank_placeholder_venues, migrations.RunPython.noop),
    ]
