# Generated by Django 5.2.17 on 2026-09-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_scopus_sync_drop_impact'),
        ('core', '0062_scout_run'),
    ]

    operations = [
    ]
