# Generated by Django 5.2.17 on 2026-09-28 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_merge_0062_scopus_sync_drop_impact_0062_scout_run'),
        ('core', '0063_schedule_integrity_and_backup'),
    ]

    operations = [
    ]
