# Generated by Django 5.2.17 on 2026-09-28 15:18

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_merge_20260928_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalWatch',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('issn', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_watches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
