# Generated by Django 5.2.17 on 2026-09-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_journal_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorship',
            name='is_corresponding',
            field=models.BooleanField(default=False),
        ),
    ]
