# Generated by Django 5.2.17 on 2026-09-28 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_authorship_corresponding'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_posts', to='core.publication'),
        ),
    ]
