# Generated by Django 5.2.17 on 2026-09-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_feedpost_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='welcome_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
