# Generated by Django 5.2.17 on 2026-09-28 23:28

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_feedpost_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationMerge',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('kept_id', models.CharField(db_index=True, max_length=32)),
                ('removed_id', models.CharField(db_index=True, max_length=32)),
                ('reason', models.CharField(blank=True, default='', max_length=32)),
                ('snapshot_json', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
