# Generated by Django 5.2.17 on 2026-09-28 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_schedule_email_batch'),
        ('core', '0068_user_welcome_seen'),
    ]

    operations = [
    ]
