# Generated by Django 5.2.17 on 2026-09-28 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_publication_merge'),
        ('core', '0069_merge_20260929_0459'),
    ]

    operations = [
    ]
