# Generated by Django 5.2.17 on 2026-09-29 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_user_staff_id_ci_unique'),
        ('core', '0070_merge_0068_publication_merge_0069_merge_20260929_0459'),
    ]

    operations = [
    ]
