# Generated by Django 5.2.17 on 2026-09-30 04:20

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_merge_20260929_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendBackRecord',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, default='')),
                ('marks_json', models.TextField(default='[]')),
                ('checklist_json', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_backs', to='core.claimaction')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_backs', to='core.claim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_backs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewMark',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('page', models.PositiveIntegerField(blank=True, null=True)),
                ('rect_x', models.FloatField(blank=True, null=True)),
                ('rect_y', models.FloatField(blank=True, null=True)),
                ('rect_w', models.FloatField(blank=True, null=True)),
                ('rect_h', models.FloatField(blank=True, null=True)),
                ('quote', models.TextField(blank=True, default='')),
                ('kind', models.CharField(choices=[('ISSUE', 'Issue'), ('OK', 'OK'), ('NOTE', 'Note')], default='ISSUE', max_length=8)),
                ('audience', models.CharField(choices=[('CLAIMANT', 'For the claimant'), ('STAFF', 'Staff only')], default='CLAIMANT', max_length=10)),
                ('checklist_key', models.CharField(blank=True, choices=[('affiliation', 'Affiliation'), ('author_position', 'Author position'), ('sec_refs', 'SEC references'), ('indexing', 'Indexing'), ('quartile', 'Quartile'), ('duplicate', 'Duplicate'), ('other', 'Other')], default='', max_length=24)),
                ('body', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_back_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_in_resubmission', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_marks', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_marks', to='core.claim')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_marks_resolved', to=settings.AUTH_USER_MODEL)),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_marks', to='core.claimattachment')),
            ],
            options={
                'ordering': ['upload_id', 'page', 'rect_y', 'created_at'],
                'indexes': [models.Index(fields=['claim', 'audience'], name='core_review_claim_i_fe4d21_idx')],
            },
        ),
    ]
