# Generated by Django 5.2.17 on 2026-09-30 04:47

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_merge_20260929_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='research_absorbed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='formulaconfig',
            name='research_year_start_month',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.CreateModel(
            name='ResearchThreshold',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('effective_from', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_thresholds_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_thresholds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from', '-created_at'],
                'indexes': [models.Index(fields=['user', '-effective_from'], name='core_resear_user_id_371daf_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('amount__gte', 0), _connector='OR'), name='research_threshold_non_negative')],
            },
        ),
    ]
