# Generated by Django 5.2.17 on 2026-09-30 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_claim_assigned_to'),
        ('core', '0072_review_marks'),
    ]

    operations = [
    ]
