# Generated by Django 5.2.17 on 2026-09-30 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_merge_0072_claim_assigned_to_0072_review_marks'),
        ('core', '0073_research_threshold'),
    ]

    operations = [
    ]
