# Generated by Django 5.2.17 on 2026-10-02 04:37

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_safeguards'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsage',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, default='', max_length=32)),
                ('feature', models.CharField(db_index=True, max_length=64)),
                ('model', models.CharField(blank=True, default='', max_length=96)),
                ('tier', models.CharField(blank=True, default='', max_length=16)),
                ('outcome', models.CharField(db_index=True, max_length=16)),
                ('code', models.CharField(blank=True, default='', max_length=32)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('prompt_chars', models.PositiveIntegerField(default=0)),
                ('output_chars', models.PositiveIntegerField(default=0)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('tokens_exact', models.BooleanField(default=False)),
                ('guard_hits', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='aiusage_user_when'), models.Index(fields=['created_at', 'outcome'], name='aiusage_when_outcome')],
            },
        ),
    ]
