# Generated by Django 5.2.17 on 2026-10-02 04:31

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_safeguards'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=48)),
                ('target_id', models.CharField(max_length=64)),
                ('rating', models.SmallIntegerField()),
                ('comment', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to='core.claim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'feature', 'target_id'), name='one_ai_feedback_per_answer')],
            },
        ),
        migrations.CreateModel(
            name='AIPrecheck',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('input_hash', models.CharField(max_length=64)),
                ('result_json', models.TextField(default='{}')),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('host', models.CharField(blank=True, default='', max_length=255)),
                ('hosted', models.BooleanField(default=False)),
                ('tokens_in', models.IntegerField(blank=True, null=True)),
                ('tokens_out', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_prechecks', to='core.claim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_prechecks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('claim', 'input_hash'), name='one_ai_precheck_per_inputs')],
            },
        ),
    ]
