# Generated by Django 5.2.17 on 2026-10-02 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_ai_precheck'),
        ('core', '0076_ai_usage'),
    ]

    operations = [
    ]
