# Generated by Django 5.2.17 on 2026-10-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_schedule_offsite_backup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilechangerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Waiting for the research office'), ('APPROVED', 'Applied'), ('DECLINED', 'Declined')], db_index=True, default='PENDING', max_length=16),
        ),
    ]
