# Generated by Django 5.2.17 on 2026-10-06 23:19

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_profilechangerequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompassState',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('portrait_json', models.TextField(blank=True, default='')),
                ('paths_json', models.TextField(blank=True, default='')),
                ('chosen_path', models.CharField(blank=True, default='', max_length=32)),
                ('plan_json', models.TextField(blank=True, default='')),
                ('facts_hash', models.CharField(blank=True, default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compass', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
