# Generated by Django 5.2.17 on 2026-10-07 01:24

import core.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_compassstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalFlagList',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('SCOPUS_DISCONTINUED', 'Scopus discontinued list'), ('HIJACKED', 'Hijacked journals list'), ('OTHER', 'Other list')], db_index=True, max_length=24)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('issn', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('domain', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('loaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
