# Generated by Django 5.2.17 on 2026-10-07 04:01

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_journalflaglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofFile',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('ARTICLE', 'Published article'), ('REFERENCE', 'SEC reference'), ('OTHER', 'Other')], default='ARTICLE', max_length=16)),
                ('filename', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=255)),
                ('content_hash', models.CharField(max_length=64)),
                ('size', models.IntegerField(default=0)),
                ('doi_found', models.CharField(blank=True, default='', max_length=255)),
                ('title_found', models.TextField(blank=True, default='')),
                ('checks_json', models.TextField(default='[]')),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_files', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proof_files', to='core.publication')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'content_hash'), name='prooffile_owner_hash_unique')],
            },
        ),
    ]
