# Generated by Django 5.2.17 on 2026-10-07 06:12

import core.models
import django.db.models.deletion
from datetime import datetime, time, timedelta

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone

NAME = "google-calendar-sync-daily"


def schedule_daily_sync(apps, schema_editor):
    """Register the daily pass (core.tasks.sync_google_calendars).

    It catches what no edit queues a sync for: a deadline that has passed, a
    month that has turned, a college date the ERP import moved. With nobody
    connected it finds no links and does nothing.
    """
    try:
        Schedule = apps.get_model("django_q", "Schedule")
    except LookupError:
        return
    if Schedule.objects.filter(name=NAME).exists():
        return
    first = timezone.make_aware(datetime.combine(timezone.localdate() + timedelta(days=1), time(5, 30)))
    Schedule.objects.create(name=NAME, func="core.tasks.sync_google_calendars", schedule_type="D",
                            repeats=-1, next_run=first)


def unschedule_daily_sync(apps, schema_editor):
    try:
        Schedule = apps.get_model("django_q", "Schedule")
    except LookupError:
        return
    Schedule.objects.filter(name=NAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_prooffile'),
        ("django_q", "0019_alter_task_options_alter_ormq_key_alter_ormq_lock_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarLink',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('google_email', models.CharField(blank=True, default='', max_length=254)),
                ('calendar_id', models.CharField(blank=True, default='', max_length=255)),
                ('refresh_token_enc', models.TextField()),
                ('scope', models.TextField(blank=True, default='')),
                ('event_map', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('needs_reconnect', models.BooleanField(default=False)),
                ('sync_started_at', models.DateTimeField(blank=True, null=True)),
                ('resync', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_link', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(schedule_daily_sync, unschedule_daily_sync),
    ]
