# Generated by Django 5.2.17 on 2026-10-07 06:09

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_googlecalendarlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='organiser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='speaker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='kind',
            field=models.CharField(choices=[('PAYOUT_RUN', 'Payout run'), ('SUBMISSION_WINDOW', 'Submission window'), ('DEADLINE', 'Deadline'), ('MEETING', 'Meeting'), ('SEMINAR', 'Seminar'), ('WORKSHOP', 'Workshop'), ('CONFERENCE', 'Conference'), ('FDP', 'Faculty development programme'), ('CALL_FOR_PAPERS', 'Call for papers'), ('OTHER', 'Something else')], db_index=True, default='OTHER', max_length=24),
        ),
        migrations.CreateModel(
            name='EventRsvp',
            fields=[
                ('id', models.CharField(default=core.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='core.calendarevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rsvps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='one_rsvp_per_person_per_event')],
            },
        ),
    ]
